baseURL = "https://www.georgpueschel.de/"
languageCode = "de-de"
title = "Georg Püschel"
theme = "github-style"
# googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Georg Püschel"
  description = "AI, robots, CNCF"
  github = "gpue"
  twitter = "gpue"
  linkedin = "gpuesch"
  huggingface = "gpue"
  email = "georg.pueschel@gmail.com"
  url = "https://gpue.github.io"
  keywords = "software, cloud, robots, kubernetes, devops, start-up, AI, CNCF, Wandelbots"
  rss = false
  lastmod = true
  favicon = "/images/github.png"
  location = "Germany"
  avatar = "/avatar.png"

  [[params.links]]
    title = "Wandelbots"
    href = "https://www.wandelbots.com"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]